#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import h5py
import os
os.system("clear")

x = h5py.File("sny_merg.hdf5")
y = x['mergerinfo']['snapshot_085']['SnapNums'][()]
print("""

                    Available snaps:

""",y)

id = int(input("""

             What Galaxy Index would you like to access?

                             """))

snapid = 12

print("""

             At a redshift 0, or snapshot 135, the corresponding ID is:

                                         """,x['mergerinfo']['snapshot_103']['Tree_SFID_grid'][id][snapid][()])

rep = input("""

            Would you like to find progenitors for this galaxy? (y or n)

                                       """)
os.system("clear")
i = 0
if rep == 'y':
    print("Progenitors:")
    print("""
_________________________________________________________""")
    while i < 13:
        pro = x['mergerinfo']['snapshot_103']['Tree_SFID_grid'][id][i][()]
        print(pro," (Snap ID:",i+1,")")
        i += 1
    print("""


            Snap ID            Redshift
_________________________________________________________

       1  (Snapshot 35)    :   z = 9.0
       2  (Snapshot 38)    :   z = 8.0
       3  (Snapshot 41)    :   z = 7.0
       4  (Snapshot 45)    :   z = 6.0
       5  (Snapshot 49)    :   z = 5.0
       6  (Snapshot 54)    :   z = 4.0
       7  (Snapshot 60)    :   z = 3.0
       8  (Snapshot 64)    :   z = 2.5
       9  (Snapshot 68)    :   z = 2.0
       10  (Snapshot 75)   :   z = 1.5
       11  (Snapshot 85)   :   z = 1.0
       12  (Snapshot 103)  :   z = 0.5
       13  (Snapshot 135)  :   z = 0.0
_________________________________________________________
    """)
elif rep == 'n':
    exit()
else:
    exit()
